# Netlify configuration for GitHub Pages mirror
# Source: GitHub Pages (neurablaze.github.io/flappy)
# This mirrors the GitHub Pages deployment

[build]
  publish = "dist"
  command = "npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "18"

# SPA routing support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom headers for better caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"